title: Lydia Kwao
email: lmkwao122@gmail.com 
phone: +233240080460
github_username: Lydia-K-dir
linkedin_url: https://www.linkedin.com/in/lydia-kwao112/
show_downloads: false
theme: jekyll-theme-minimal
